# 使用 Python 官方镜像作为基础镜像
FROM python:3.10-slim

# 设置工作目录
WORKDIR /app

# 复制当前目录内容到工作目录
COPY . .

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt

# 运行 Celery Worker
CMD ["celery", "-A", "tasks.Celery_app", "worker", "-l", "INFO", "--pool=solo"]
